Repository adorableco/Fit_Friends, pull requests merged in 2025-03, with the labels that each got.

#101 FITFRND-42 매치 생성 오류 해결
  back/.gitignore
  back/match-service/build.gradle
  back/match-service/src/main/java/com/example/match_service/client/dto/MatchCreateRequest.java
  back/match-service/src/main/java/com/example/match_service/common/auth/SecurityConfig.java
  back/match-service/src/main/java/com/example/match_service/common/config/FeignConfig.java
  back/match-service/src/main/java/com/example/match_service/controller/MatchController.java
  back/match-service/src/main/java/com/example/match_service/controller/ParticipationController.java
  back/match-service/src/main/java/com/example/match_service/domain/Match.java
  back/match-service/src/main/java/com/example/match_service/service/MatchService.java
  back/match-service/src/main/resources/application.yml
  back/match-service/src/test/java/com/example/match_service/service/MatchServiceTest.java
  back/post-service/src/main/resources/application.yml
  back/user-service/src/main/java/com/example/userservice/client/MatchServiceClient.java
  back/user-service/src/main/java/com/example/userservice/client/dto/ParticipationResponse.java
  back/user-service/src/main/java/com/example/userservice/common/config/FeignConfig.java
  back/user-service/src/main/java/com/example/userservice/controller/UserController.java
  back/user-service/src/main/java/com/example/userservice/service/UserService.java
  back/user-service/src/main/resources/application.yml
Labels: 🛠️ Fix

#98 FITFRND-27 user-service와 match-service 연결
  back/.gitignore
  back/match-service/build.gradle
  back/match-service/src/main/java/com/example/match_service/controller/MatchController.java
  back/match-service/src/main/java/com/example/match_service/controller/ParticipationController.java
  back/post-service/src/main/resources/application.yml
  back/user-service/src/main/java/com/example/userservice/client/MatchServiceClient.java
  back/user-service/src/main/java/com/example/userservice/client/dto/ParticipationResponse.java
  back/user-service/src/main/java/com/example/userservice/common/config/FeignConfig.java
  back/user-service/src/main/java/com/example/userservice/controller/UserController.java
  back/user-service/src/main/java/com/example/userservice/service/UserService.java
  back/user-service/src/main/resources/application.yml
Labels: ✨ Feature

#103 Feat/fitfrnd 27
  back/apigateway-service/build.gradle
  back/apigateway-service/src/main/resources/application.yml
  back/user-service/src/main/java/com/example/userservice/common/auth/SecurityConfig.java
  back/user-service/src/main/java/com/example/userservice/common/dto/CustomResponseBody.java
  back/user-service/src/main/resources/application.yml
Labels: 🛠️ Fix, ✨ Feature

#105 Feat/fitfrnd 28
  back/apigateway-service/src/main/resources/application.yml
  back/match-service/src/main/resources/application.yml
  back/post-service/build.gradle
  back/post-service/src/main/java/com/example/postservice/PostServiceApplication.java
  back/post-service/src/main/java/com/example/postservice/client/dto/SaveMatchRequest.java
  back/post-service/src/main/java/com/example/postservice/client/dto/SaveMatchResponse.java
  back/post-service/src/main/java/com/example/postservice/common/config/FeignConfig.java
  back/post-service/src/main/java/com/example/postservice/common/dto/CustomResponseBody.java
  back/post-service/src/main/java/com/example/postservice/dto/PostIdResponse.java
  back/post-service/src/main/java/com/example/postservice/service/PostService.java
Labels: 🛠️ Fix, ✨ Feature

#109 Feat/fitfrnd 46
  back/apigateway-service/src/main/java/com/example/apigatewayservice/common/config/CorsConfig.java
  back/apigateway-service/src/main/java/com/example/apigatewayservice/common/config/WebConfig.java
  back/post-service/src/main/java/com/example/postservice/controller/PostController.java
  back/user-service/src/main/java/com/example/userservice/controller/AuthController.java
  back/user-service/src/main/java/com/example/userservice/controller/UserController.java
Labels: ✨ Feature

#111 FITFRND-47 match의 tag 조회 기능 구현
  back/post-service/src/main/java/com/example/postservice/controller/PostController.java
  back/post-service/src/main/java/com/example/postservice/dto/TagByPostResponse.java
  back/post-service/src/main/java/com/example/postservice/repository/PostRepository.java
  back/post-service/src/main/java/com/example/postservice/service/PostService.java
Labels: ✨ Feature

#112 Feat/fitfrnd 44
  back/match-service/src/main/java/com/example/match_service/client/PostServiceClient.java
  back/match-service/src/main/java/com/example/match_service/client/dto/PostTagResponse.java
  back/match-service/src/main/java/com/example/match_service/client/dto/UserTagResponse.java
  back/match-service/src/main/java/com/example/match_service/common/dto/CustomResponseBody.java
  back/match-service/src/main/java/com/example/match_service/common/exception/NotValidUserForMatchException.java
  back/match-service/src/main/java/com/example/match_service/controller/AttendanceController.java
  back/match-service/src/main/java/com/example/match_service/controller/ParticipationController.java
  back/match-service/src/main/java/com/example/match_service/domain/Match.java
  back/match-service/src/main/java/com/example/match_service/domain/Participation.java
  back/match-service/src/main/java/com/example/match_service/service/ParticipationService.java
  back/match-service/src/test/java/com/example/match_service/service/ParticipationServiceTest.java
Labels: ✨ Feature, ✅ Test

#114 FITFRND-48 coderabbit-action 워크플로우
  .coderabbit.yaml
  .github/workflows/coderabbit-review.yml
Labels: ✨ Feature, AIReview

#116 FITFRND-49 update 기능 test
  .github/workflows/coderabbit-review.yml
  back/post-service/src/main/java/com/example/postservice/domain/Post.java
  back/post-service/src/main/java/com/example/postservice/service/PostService.java
  back/post-service/src/test/java/com/example/postservice/domain/PostTest.java
Labels: ✅ Test

#121 Docs/fitfrnd 51
  back/user-service/build.gradle
  back/user-service/src/main/java/com/example/userservice/controller/AuthController.java
  back/user-service/src/main/java/com/example/userservice/controller/UserController.java
  back/user-service/src/main/resources/smart-doc.json
  back/user-service/src/main/resources/static/AllInOne.css
  back/user-service/src/main/resources/static/font.css
  back/user-service/src/main/resources/static/highlight.min.js
  back/user-service/src/main/resources/static/index.adoc
  back/user-service/src/main/resources/static/index.html
  back/user-service/src/main/resources/static/jquery.min.js
  back/user-service/src/main/resources/static/search.js
Labels: 📃 Docs, AIReview

#123 FITFRND-39 docker container 구성
  back/apigateway-service/Dockerfile
  back/apigateway-service/gradlew
  back/apigateway-service/src/main/resources/application.yml
  back/discovery-service/Dockerfile
Labels: ✨ Feature, AIReview

#129 FITFRND-54 ai-review workflow 변경
  .coderabbit.yaml
  .github/workflows/ai-review.yml
  .github/workflows/coderabbit-review.yml
Labels: ✨ Feature, AIReview

#135 FITFRND-56 gemini max token 초과 오류 해결
  dist/index.js
  src/gemini/GeminiClient.ts
Labels: 🛠️ Fix

#133 FITFRND-55 모집글 조회/모집글 등록/마이 페이지 디자인 개선 및 네비게이션 바 추가
  front/App.js
  front/navigation/BottomTabNavigator.js
  front/package-lock.json
  front/package.json
  front/screens/HomeScreen.js
  front/screens/MatchListScreen.js
  front/screens/MyMatchList.js
  front/screens/MyMatchListScreen.js
  front/screens/PostingScreen.js
  front/screens/UserDetailScreen.js
Labels: ✨ Feature, AIReview
